# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=70)),
                ('picture', models.FileField(blank=True, null=True, upload_to='static/')),
            ],
        ),
    ]
